#! /bin/bash -
# auto setup vim on ubuntu
LC_ALL=C
# BEGIN Tool Functions
. $(dirname $0)/pffs
# END Tool Functions

setupvim(){
	local fileDir="/etc/vim/vimrc.local";
	local templateFileDir=${pffs_var_templateFolderName}"/etc.vim.vimrc.local";
	ifYesDo "apt-get install  -y vim"; # install vim
	ifYesDo "mustBeExist ${fileDir}; cp ${fileDir} ${fileDir}".bak"; cat ${templateFileDir} > ${fileDir}"; # config vim.;
	ifYesDo "git config core.editor vim"; # config editor for git;
}
setupvim;
