#! /bin/bash -
# auto setup vim on ubuntu
LC_ALL=C
# BEGIN Tool Functions
. $(dirname $0)/pffs
# END Tool Functions

setupvim(){
	local fileDir="/etc/vim/vimrc.local";
	local templateFileDir=${pffs_var_templateFolderName}"/etc.vim.vimrc.local";
	local vimVersion=$(vim --version | grep "Vi IMproved"| awk '{print $(5)}');
	local colorFileDir="/usr/share/vim/vim${vimVersion/./}/colors/leerkan.vim"
	local templateColorFileDir=${pffs_var_templateFolderName}"/usr.share.vim.vim73.colors.leerkan.vim";
	ifYesDo "apt-get install  -y vim" "" "install vim now"; # install vim
	ifYesDo "mustBeExist ${colorFileDir}; cp ${colorFileDir} ${colorFileDir}".bak"; cat ${templateColorFileDir} > ${colorFileDir}" "" "Add colorscheme:Leerkan"; # add color file.;
	ifYesDo "mustBeExist ${fileDir}; cp ${fileDir} ${fileDir}".bak"; cat ${templateFileDir} > ${fileDir}"; # config vim.;
	ifYesDo "git config core.editor vim"; # config editor for git;
}
setupvim;
